# Generated by Django 5.1.3 on 2024-12-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_wishlist_created_at'),
        ('home', '0002_remove_wishlist_product_wishlistitem'),
    ]

    operations = [
    ]
