# Generated by Django 5.1.3 on 2024-12-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_wishlist_unique_together'),
        ('home', '0004_wishlist_created_at_wishlist_product'),
    ]

    operations = [
    ]
