# Generated by Django 5.1.3 on 2025-01-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='carousel_image',
        ),
    ]
