# Generated by Django 5.1.3 on 2025-01-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
