# Generated by Django 5.1.3 on 2024-12-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
        ('account', '0002_initial'),
    ]

    operations = [
    ]
