# Generated by Django 5.1.3 on 2024-12-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
