# Generated by Django 5.1.3 on 2024-12-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=20),
        ),
    ]
