# Generated by Django 5.1.3 on 2025-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'cod'), ('stripe', 'Stripe')], default='cod', max_length=20),
        ),
    ]
